### ISSUE TITLE
what is difference after distortion removing

### ISSUE THREAD

**Issue by xiaoyuanzh** [BIT-MJY/occupancy_grid_mapping#1]
hi.  what is the difference in the two png?

**Comment by BIT-MJY** [comment]
> hi. what is the difference in the two png?

because the bag includes a small robot's slow motion in Gazebo so the effect is not apparent. you can use another bag to verify this. Please refer to this link: https://blog.csdn.net/weixin_44684139/article/details/105657081

**Comment by xiaoyuanzh** [comment]
hi.   我发现在，深蓝课程的代码，scan callback 数据是从beamnum递减的。
在您的callback数据是递增了，这两者有什么区别吗？

**Comment by BIT-MJY** [comment]
> hi. 我发现在，深蓝课程的代码，scan callback 数据是从beamnum递减的。
> 在您的callback数据是递增了，这两者有什么区别吗？

没有区别，顺序倒序处理都可以的，重点是需要获取点对应的位姿。

**Comment by xiaoyuanzh** [comment]
哥们，方便加个微信聊？
实际测试中发现方向等问题

**Comment by BIT-MJY** [comment]
> 哥们，方便加个微信聊？
> 实际测试中发现方向等问题

ok~   BIT_MJY

**Comment by BIT-MJY** [comment]
感谢您的关注，现在关闭此问题。若您有新的问题可以随时提问。
